export const SUCCESSFUL_GET_API_INFORMATION = 'SUCCESSFUL_GET_API_INFORMATION';
export const FAILED_GET_API_INFORMATION = 'FAILED_GET_API_INFORMATION';
export const SET_CHALLENGE_STATE = 'SET_CHALLENGE_STATE';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
export const SWITCH_LOADING = 'SWITCH_LOADING';
export const SET_COUNTERS = 'SET_COUNTERS';
export const SET_INITIAL_TIME = 'SET_INITIAL_TIME';
export const SET_END_TIME = 'SET_END_TIME';
